# Generated by Django 4.2.11 on 2024-04-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('cognom', models.CharField(max_length=100)),
                ('assignatures', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
            ],
        ),
    ]
